name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x' 

    - name: remove node modules
      run: rm -rf node_modules

    - name: remove package.json
      run: rm package-lock.json
      
    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test